name: Build LaTeX (Tag)

on:
  push:
    tags:
      - v*

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v2
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: language
          root_file: sygus.tex
          pre_compile: tlmgr update --self && tlmgr update --all
      - name: Delete Old Drafts
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: language/sygus.pdf
          draft: false
          name: SyGuS Language (${{ github.event.release.tag_name }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
